# Generated by Django 2.2.5 on 2020-04-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('vid', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('relevance', models.FloatField()),
                ('impact', models.FloatField()),
                ('score', models.FloatField()),
                ('relation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=300)),
                ('year', models.IntegerField()),
                ('citation', models.IntegerField()),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=250)),
                ('authors', models.CharField(max_length=300)),
            ],
        ),
    ]
